uses libevent-dev if installed, only runs autogen.sh if found

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,116 +1,137 @@
 #!/usr/bin/env bash
 
 construct_configure_options() {
-  load_configure_options
+    load_configure_options
 
-  if [ "$TMUX_CONFIGURE_OPTIONS" = "" ]; then
-    local configure_options="--prefix=$install_path"
+    # shellcheck disable=SC2154
+    if [[ "$TMUX_CONFIGURE_OPTIONS" = "" ]]; then
+        local configure_options="--prefix=$install_path"
 
-    if [ "$TMUX_EXTRA_CONFIGURE_OPTIONS" != "" ]; then
-      configure_options="$configure_options $TMUX_EXTRA_CONFIGURE_OPTIONS"
+        if [[ "$TMUX_EXTRA_CONFIGURE_OPTIONS" != "" ]]; then
+            configure_options="$configure_options $TMUX_EXTRA_CONFIGURE_OPTIONS"
+        fi
+    else
+        local configure_options="$TMUX_CONFIGURE_OPTIONS --prefix=$install_path"
     fi
-  else
-    local configure_options="$TMUX_CONFIGURE_OPTIONS --prefix=$install_path"
-  fi
 
-  echo "$configure_options"
+    echo "$configure_options"
 }
 
 load_configure_options() {
-  local asdf_tmux_configure_options="${HOME}/.asdf-tmux-configure-options"
+    local asdf_tmux_configure_options="${HOME}/.asdf-tmux-configure-options"
 
-  if [[ ! -r "$asdf_tmux_configure_options" ]]; then
-    return
-  fi
+    if [[ ! -r "$asdf_tmux_configure_options" ]]; then
+        return
+    fi
 
-  set -a
-  source "$asdf_tmux_configure_options"
-  set +a
+    set -a
+    # shellcheck source=/dev/null
+    source "$asdf_tmux_configure_options"
+    set +a
 }
 
 install_tmux() {
-  local version=$1
-  local install_path=$2
-  local concurrency=$3
+    local version=$1
+    local install_path=$2
+    local concurrency=$3
+    local tmp_download_dir
+    local source_path
 
-  if [ "$TMPDIR" = "" ]; then
-    local tmp_download_dir=$(mktemp -d -t tmux_build_XXXXXX)
-  else
-    local tmp_download_dir=$TMPDIR
-  fi
-
-  # path to the tar file
-  local source_path=$(get_download_file_path $version $tmp_download_dir)
-  echo $source_path
-  download_source_file $version $source_path
-
-  # running this in subshell
-  # we don't want to disturb current working dir
-  (
-    if ! type "unzip" &>/dev/null; then
-      echo "ERROR: unzip not found"
-      exit 1
+    if [[ "$TMPDIR" = "" ]]; then
+        tmp_download_dir=$(mktemp -d -t tmux_build_XXXXXX)
+    else
+        tmp_download_dir=$TMPDIR
     fi
 
-    unzip -q $source_path -d $tmp_download_dir || exit 1
+    # path to the tar file
+    source_path=$(get_download_file_path "$version" "$tmp_download_dir")
+    echo "$source_path"
+    download_source_file "$version" "$source_path"
 
-    cd $tmp_download_dir/tmux-${version}
-    ./autogen.sh
-    install_path=$install_path
-    ./configure $(construct_configure_options) CFLAGS="-I${install_path}/include" LDFLAGS="-L${install_path}/lib -Wl,-rpath,$install_path/lib"
-    make -j $concurrency
-    if [[ $? -eq 0 ]]; then
-      make install
-    fi
-  )
+    # running this in subshell
+    # we don't want to disturb current working dir
+    (
+        if ! type "unzip" &>/dev/null; then
+            echo "ERROR: unzip not found"
+            exit 1
+        fi
+
+        unzip -q "$source_path" -d "$tmp_download_dir" || exit 1
+
+        cd "$tmp_download_dir/tmux-${version}" || exit
+
+        scr_autogen="./autogen.sh"
+        if [[ -f "$scr_autogen" ]]; then
+            "$scr_autogen"
+        else
+            echo
+            echo "><> No $scr_autogen found, skipping"
+            echo
+        fi
+
+        # install_path=$install_path
+        ./configure "$(construct_configure_options)" CFLAGS="-I${install_path}/include" LDFLAGS="-L${install_path}/lib -Wl,-rpath,$install_path/lib"
+        make -j "$concurrency" && make install
+    )
 }
 
 install_libevent() {
-  local install_path=$1
-  local concurrency=$2
+    local install_path=$1
+    local concurrency=$2
+    local tmp_download_dir
 
-  if [ "$TMPDIR" = "" ]; then
-    local tmp_download_dir=$(mktemp -d -t tmux_build_XXXXXX)
-  else
-    local tmp_download_dir=$TMPDIR
-  fi
-  cd $tmp_download_dir
+    if [[ "$TMPDIR" = "" ]]; then
+        tmp_download_dir=$(mktemp -d -t tmux_build_XXXXXX)
+    else
+        tmp_download_dir=$TMPDIR
+    fi
+    cd "$tmp_download_dir" || echo "ERROR: Failed to cd $tmp_download_dir"
 
-  libevent_version="2.1.10"
+    libevent_version="2.1.10"
 
-  curl -LO https://github.com/libevent/libevent/releases/download/release-${libevent_version}-stable/libevent-${libevent_version}-stable.tar.gz
-  tar -zxf libevent-${libevent_version}-stable.tar.gz
-  cd libevent-${libevent_version}-stable
-  ./configure --prefix=$install_path
-  make -j $concurrency
-  if [[ $? -eq 0 ]]; then
-    make install
-  else
-    exit 2
-  fi
+    curl -LO "https://github.com/libevent/libevent/releases/download/release-${libevent_version}-stable/libevent-${libevent_version}-stable.tar.gz"
+    tar -zxf libevent-"${libevent_version}"-stable.tar.gz
+    cd libevent-"${libevent_version}"-stable || exit
+    ./configure --prefix="$install_path"
+
+    if make -j "$concurrency"; then
+        make install
+    else
+        exit 2
+    fi
 }
 
 download_source_file() {
-  local version=$1
-  local download_path=$2
-  local download_url=$(get_download_url $version)
+    local version=$1
+    local download_path=$2
+    local download_url
 
-  curl -Lo $download_path -C - $download_url
+    download_url=$(get_download_url "$version")
+    echo "><> will download: $download_url"
+    curl -Lo "$download_path" -C - "$download_url"
 }
 
 get_download_file_path() {
-  local version=$1
-  local tmp_download_dir=$2
+    local version=$1
+    local tmp_download_dir=$2
 
-  echo "$tmp_download_dir/tmux-${version}.zip"
+    echo "$tmp_download_dir/tmux-${version}.zip"
 }
 
 get_download_url() {
-  local version=$1
+    local version=$1
 
-  echo "https://github.com/tmux/tmux/archive/${version}.zip"
+    echo "https://github.com/tmux/tmux/archive/${version}.zip"
 }
 
-install_libevent $ASDF_INSTALL_PATH $ASDF_CONCURRENCY
+if [[ ! -f /usr/include/event.h ]]; then
+    # shellcheck disable=SC2154
+    install_libevent "$ASDF_INSTALL_PATH" "$ASDF_CONCURRENCY"
+else
+    echo
+    echo "><> libevent-dev package is installed, no need to install separately"
+    echo
+fi
 
-install_tmux $ASDF_INSTALL_VERSION $ASDF_INSTALL_PATH $ASDF_CONCURRENCY
+# shellcheck disable=SC2154
+install_tmux "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH" "$ASDF_CONCURRENCY"
